// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication3.Models;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(LabDBContext))]
    partial class LabDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication3.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__4A311D2FB30E6136");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("WebApplication3.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Bill_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<bool>("BillPaid")
                        .HasColumnType("bit")
                        .HasColumnName("BillPaid");

                    b.Property<decimal>("Costs")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PhoneNumber1")
                        .HasColumnType("varchar(15)");

                    b.HasKey("BillId")
                        .HasName("PK__Bills__CF6F718BF824A4E8");

                    b.HasIndex("PhoneNumber1");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("WebApplication3.Models.Call", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Call_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallId"));

                    b.Property<int?>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("Bill_id");

                    b.Property<DateTime>("CallTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CallTime");

                    b.Property<decimal>("Costs")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("Duration");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit")
                        .HasColumnName("Paid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("CallId")
                        .HasName("PK__Calls__19E7F093973A4759");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("WebApplication3.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Client_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Afm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AFM");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("ClientId")
                        .HasName("PK__Clients__75A2D320B56299E0");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__Clients__85FB4E385F5B0B7A")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApplication3.Models.Phone", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime>("ProgramEnds")
                        .HasColumnType("datetime2")
                        .HasColumnName("ProgramEnds");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ProgramName");

                    b.Property<bool>("ProgramPaid")
                        .HasColumnType("bit")
                        .HasColumnName("ProgramPaid");

                    b.HasKey("PhoneNumber")
                        .HasName("PK__Phones__85FB4E392FAA14E1");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("WebApplication3.Models.Programme", b =>
                {
                    b.Property<string>("ProgramName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Benefits")
                        .HasColumnType("text");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ProgramName")
                        .HasName("PK__Programs__4F925711C949785D");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("WebApplication3.Models.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seller_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("SellerId")
                        .HasName("PK__Sellers__016148B16AE97788");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("WebApplication3.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__206A9DF8876E0A22");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E43BDEACBF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication3.Models.Admin", b =>
                {
                    b.HasOne("WebApplication3.Models.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Admin__User_id__6E01572D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication3.Models.Bill", b =>
                {
                    b.HasOne("WebApplication3.Models.Phone", null)
                        .WithMany("Bills")
                        .HasForeignKey("PhoneNumber1");
                });

            modelBuilder.Entity("WebApplication3.Models.Client", b =>
                {
                    b.HasOne("WebApplication3.Models.User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Clients__User_id__71D1E811");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication3.Models.Seller", b =>
                {
                    b.HasOne("WebApplication3.Models.User", "User")
                        .WithMany("Sellers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Sellers__User_id__6B24EA82");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication3.Models.Phone", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("WebApplication3.Models.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Clients");

                    b.Navigation("Sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
